### ISSUE TITLE
Not getting data / Login Error

### ISSUE THREAD

**Issue by cyriax** [Skipperro/pajgps-homeassistant#10]
Hello!

i've seen several errors in the log today:

`"error" from custom_components/pajgps/device_tracker.py:333`
and
`"No data for PAJ GPS device XXXXXXX" from custom_components/pajgps/device_tracker.py:292`

The app didn't work either but the website did just fine so I waved it off.

Suddenly the finder app gave me message about a new security concept implemented by PAJ resulting in the need for changing my password. The login in the app and portal seems to work just fine now but additionally to the previous errors I now get

`"Could not get login token" from custom_components/pajgps/device_tracker.py:435`

after reconfiguring the integration.

So I guess they changed something in the API or authentification methods. Still hoping this is just temporary but just in case...

Thanks!

**Comment by cyriax** [comment]
Played around a bit and changed the api URL to https://connect.paj-gps.de/api/v1/.

now i do get `Error 400 while getting login token: {'passwordError': 'Password is incorrect.'}`

using the CURL-command directly with the same credentials works and i do get a token

`curl -X 'POST'   'https://connect.paj-gps.de/api/v1/login?email=xxxxx@xxx.xx&password=xxxxxxxx'   -H 'accept: application/json'   -H 'X-CSRF-TOKEN: '   -d ''`

**Comment by cyriax** [comment]
Okay, after randomly changing around passwords und reinstalling/reconfiguring the integration it's now in a somewhat working state:

using the api URL https://connect.paj-gps.de/api/ it just gives non descriptive errors, changing it to https://connect.paj-gps.de/api/v1/ the login does work again and data is received

changing it back to the original url brings back the error so i'd call it a fix for now

**Comment by iursevla** [comment]
I have the same problem

```text
2024-11-09 18:44:42.322 ERROR (MainThread) [custom_components.pajgps.device_tracker] 'error'
2024-11-09 18:44:42.323 ERROR (MainThread) [custom_components.pajgps.device_tracker] Could not get login token
```

**Comment by iursevla** [comment]
I don't think this is fixed. Maybe PAJ changed the API endpoint to add the /v1? It's strange that it was working before 🤔 

URL without `/v1`: `{"message":"Resource not found."}`

URL with `/v1`

```json
{
  "success": {
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUz...",
    "expires_in": 2592000,
    "isAdmin": 0,
    "userID": 99999,
    "routeIcon": "circle",
    "Petsevices": 0
  }
}
```

**Comment by cyriax** [comment]
The v1 was part of the "official" api documentation for months, maybe they removed some redirects and  it was working all the time by accident

**Comment by iursevla** [comment]
@cyriax seems like it. I'll create a PR for it and let's see what the other users think of it. I'll also add more logs (debug level to help with potential debug)

**Comment by cyriax** [comment]
@iursevla great, thank you!

**Comment by Skipperro** [comment]
I'm testing the changes for old devices right now. If it will be OK, I'll merge the fix and release new version.
