### ISSUE TITLE
Code needs to be updated: async_forward_entry_setup

### ISSUE THREAD

**Issue by ahnungsbefreit** [Skipperro/pajgps-homeassistant#12]
When starting this integration (which perfectly with my device, thank you!!!) I see the following warning in the HA log:

`2024-11-26 09:48:14.807 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'pajgps' calls async_forward_entry_setup for integration, pajgps with title: PAJ GPS Tracker and entry_id: XXX, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/pajgps/__init__.py, line 28: hass.async_create_task(, please report it to the author of the 'pajgps' custom integration
2024-11-26 09:48:17.886 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration pajgps with title: PAJ GPS Tracker and entry_id: XXX, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
`

**Comment by Skipperro** [comment]
Hey, I'm glad that you find this integration useful.
Thanks for letting me know. I'll look into it and make changes to be sure it will still run in 2025. 
I will still need my devices to run, so I got motivation to fix that :smiley:

**Comment by Skipperro** [comment]
I have similar warning for my integration, but it just says that the setup function is not awaited in helpers/frame.py

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:155
Detected code that calls async_forward_entry_setup for integration pajgps with title: PAJ GPS Tracker and entry_id: XXX, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
```
If that's the same issue, then it's not something I can fix, because it refers to issue in HA itself, not the code for PAJ GPS.

I will have to investigate it further and contact HA-People to find out if I have to adjust my code or this will go away by itself with new version of HA.

**Comment by ahnungsbefreit** [comment]
With the latest beta, I don't see the above messages in the log anymore. Thank you for the quick fix!

**Comment by Miyamoto72** [comment]
> I have similar warning for my integration, but it just says that the setup function is not awaited in helpers/frame.py
> 
> ```
> Logger: homeassistant.helpers.frame
> Source: helpers/frame.py:155
> Detected code that calls async_forward_entry_setup for integration pajgps with title: PAJ GPS Tracker and entry_id: XXX, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
> ```
> 
> If that's the same issue, then it's not something I can fix, because it refers to issue in HA itself, not the code for PAJ GPS.
> 
> I will have to investigate it further and contact HA-People to find out if I have to adjust my code or this will go away by itself with new version of HA.

Still does occur for me with HA  Core 2025.2.5 and pajgps v0.5.0
