### ISSUE TITLE
GPS & Battery-Level not available

### ISSUE THREAD

**Issue by andreasbuff** [Skipperro/pajgps-homeassistant#6]
Hello, I love your Integration and installation worked without problem.

Unfortunatly, according to your spec description there should be two sensors, such as
 - GPS-Position and
 - Battery Level

I do have speed sensor, but the other two are missing? What can I do, or what am I doing wrong? 

Regards. Andreas

**Comment by Skipperro** [comment]
Hi @andreasbuff 
Yes, I know it may be confusing a bit. For position there is this discussion:
https://github.com/Skipperro/pajgps-homeassistant/discussions/4

For battery, please let me know which model do you have, so I can confirm that it actually have a battery.
