### ISSUE TITLE
Comprehension question: Is there a way to get the Tracker positions also on the map?

### ISSUE THREAD

**Issue by MaPaSoTo** [Skipperro/pajgps-homeassistant#8]
The integration went completely smoothly and all devices were recognised. It would be nice to see them on the map in HA as well. How do I have to proceed here so that I can see the individual trackers there?

**Comment by Skipperro** [comment]
Yes, I think this discussion can help to answer your question:
[Where to see device on the map?](https://github.com/Skipperro/pajgps-homeassistant/discussions/4)
If it's not what you are looking for, please let me know.

**Comment by MaPaSoTo** [comment]
Yes, this solves my Problem exactly. Thank you so much.
