### ISSUE TITLE
Compatibility Issue with Home Assistant Version

### ISSUE THREAD

**Issue by Genassi** [Skipperro/pajgps-homeassistant#9]
Hi,

I encountered an issue when clicking the link in the repository. I was redirected to my Home Assistant instance, where I received a message stating that the version I am using may not be compatible and that I should check if I am using the latest version.

Could you please confirm whether the version available in this repository is compatible with the latest Home Assistant release? Or should I look for a different version?

Thanks for your help!

**Comment by iursevla** [comment]
I can confirm that it works with the latest stable version. Just add this as custom repository to HACS.

**Comment by Skipperro** [comment]
Sorry for the late reply - I missed the notification about your question.
I don't know what the message was about, but I'm using right now the latest version, **2024.10.4**, and everything is working fine.
